---
- name: Install PHP on Debian/Ubuntu
  apt:
    name: 
      - php
      - php-mysql
    state: present
  when: ansible_os_family == "Debian"

- name: Install PHP on RedHat/CentOS
  yum:
    name: 
      - php
      - php-mysql
    state: present
  when: ansible_os_family == "RedHat"
