- name: Installing nginx
  yum:
    name: nginx
    state: present
    update_cache: yes

- name: Ensure /usr/share/nginx/html exists
  ansible.builtin.file:
    path: "/usr/share/nginx/html"
    state: directory

- name: Delete default index.html
  ansible.builtin.file:
    path: "/usr/share/nginx/html/index.html"
    state: absent

- name: Copy default index.html
  ansible.builtin.copy:
    src: "./files/html/index.php"  # Убедись, что у тебя есть файл index.html в этой папке
    dest: "/usr/share/nginx/html/"
    mode: "0644"

- name: Replace nginx configuration
  ansible.builtin.template:
    src: "./templates/rh.default.conf.j2"
    dest: "/etc/nginx/nginx.conf"  # В RHEL обычно используется этот путь
    mode: "0644"

- name: Start and enable Nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
