- hosts: all
  become: yes  
  tasks:
    - name: Install Nginx
      include_role:
        name: nginx
      
    - name: Install PHP
      include_role:
        name: php

    - name: Install mysql
      include_role:
        name: mysql